# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('_testrepo_rcppeigen_hello_world', PACKAGE = 'testrepo')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_testrepo_rcppeigen_outerproduct', PACKAGE = 'testrepo', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_testrepo_rcppeigen_innerproduct', PACKAGE = 'testrepo', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_testrepo_rcppeigen_bothproducts', PACKAGE = 'testrepo', x)
}

convolveCpp <- function(a, b) {
    .Call('_testrepo_convolveCpp', PACKAGE = 'testrepo', a, b)
}

